fix: reorder logic of creation of submission
ourjapanlife/findadoc-server pull request #571
Opened 2024-09-03 23:11 UTC by NabbeunNabi

Resolves #570 

# What changed
Before the function for `approveSubmission` had the order wrong on what needed to be created when approving a facility. Now a facility is created...and then the healthcare professionals if they need to be. Then finally the submission is changed to `isApproved` This is so that the correct order of logic exists. All the steps should happen in this order or it should not be approved since some some error occurred in the approval process.

# Testing instructions
A test was added to test the functionality of this functionality based on this logic order.

1.  Submission is created
2. Submission is updated to `isUnderReview`
3. Submission is updated with all the necessary values for approval.
4. Submission is approved with no errors.

2024-09-08 12:56 UTC, ermish requested changes
just one quick change and make sure it's also working with the latest updates from main around added transactions
I checked through the logic change, and it should be correct to create the facility first👍

2024-09-08 12:56 UTC, ermish commented on src/services/submissionService.ts
> +        const createFacilityResult = await createFacility(currentSubmission.facility as dbSchema.Facility)
This isn't the write input type. It should be the createFacilityInput

2024-09-08 12:56 UTC, ermish commented on src/services/submissionService.ts
> +        //set the data to return to the graphQl response
nit: this function might not be called from a resolver, so we shouldn't imply it's a graphql response

2024-09-09 12:14 UTC, theyokohamalife commented on __tests__/submissions.test.ts
> +                input: generateRandomUpdateSubmissionInput({ isUnderReview: true })
Shouldn't `isUnderReview` be `false` if a submission is approved? 🤔

2024-09-09 12:25 UTC, theyokohamalife commented
Really great work! It's always good to take the error paths into consideration when writing tests. Some suggestions for additional test cases:
1. When an ID is passed for a submission that doesn't exist
2. When an ID is passed for a submission that is already marked approved
3. When `createFacility` returns errors
4. When `createHealthcareProfessional` returns errors

2024-09-10 10:33 UTC, ermish approved these changes
Ship it!

2024-09-10 10:33 UTC, merged